import React from 'react';
import {Img,staticFile} from 'remotion';
import {a,p,m,mix,blur} from './motion';
import brand from '../config/brand.json';
import {press,done} from './interactions';
export const purple=brand.accent;
export const photo=(name:string)=>staticFile('photos/'+name+'.jpg');
export const Icon=({name='square',size=22,color='currentColor'}:{name?:string;size?:number;color?:string})=>{
 const paths:Record<string,React.ReactNode>={plus:<path d="M12 4v16M4 12h16"/>,grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,image:<><rect x="3" y="3" width="18" height="18" rx="2"/><path d="m3 17 6-6 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.2"/></>,eye:<><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,text:<><path d="M3 5h18M12 5v15M7 20h10"/></>,check:<path d="m4 12 5 5L20 6"/>,chevron:<path d="m5 9 7 7 7-7"/>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,cursor:<path d="m5 3 14 10-7 1-3 7Z"/>,star:<path d="m12 1 3 8 8 3-8 3-3 8-3-8-8-3 8-3Z"/>,layers:<><path d="m2 8 10-5 10 5-10 5Zm0 5 10 5 10-5M2 18l10 5 10-5"/></>,square:<rect x="3" y="4" width="18" height="16" rx="2"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>,globe:<><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></>,gear:<><path d="m9 3-1 3-3 1v3l-2 2 2 2v3l3 1 1 3h6l1-3 3-1v-3l2-2-2-2V7l-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/></>,mail:<><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m2 5 10 8L22 5"/></>,phone:<rect x="7" y="2" width="10" height="20" rx="2"/>};
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round">{paths[name]||paths.square}</svg>
};
export const Mark=({glow=false,size=70,t=0}:{glow?:boolean;size?:number;t?:number})=><div style={{width:size,height:size,position:'relative',filter:glow?'drop-shadow(0 0 18px #bc63ff) drop-shadow(0 0 44px #9f5dff)':'none'}}>{[0,1,2].map(i=><div key={i} style={{position:'absolute',width:`${70-i*8}%`,height:'35%',left:`${15+i*4}%`,top:`${43-i*20}%`,borderRadius:glow?size*.08:3,background:glow?'linear-gradient(115deg,#fff 4%,#f6cbff 25%,#a787ff 54%,#ecfcff 85%)':'#141321',boxShadow:glow?'inset 0 2px 1px #ffffffef,inset -3px -5px 6px #7750be99,0 7px 5px #1d072f55':'none',transform:`perspective(500px) rotateX(22deg) rotateY(-18deg) translateY(${glow?Math.sin(t*1.8+i*.7)*1.1:0}px)`}}/> )}</div>;
export const Cursor=({x,y,scale=1,click=false}:{x:number;y:number;scale?:number;click?:boolean})=><div style={{position:'absolute',left:x,top:y,zIndex:100,transform:`scale(${scale*(click?.87:1)})`,transformOrigin:'0 0',filter:'drop-shadow(0 3px 5px #0005)'}}><svg width="65" height="83" viewBox="0 0 65 83" style={{transform:"translate(-5px,-4px)",overflow:"visible"}}><path d="M5 4 54 48 33 48 47 73 34 80 21 53 6 69Z" fill="#16131f" stroke="white" strokeWidth="5" strokeLinejoin="round"/></svg></div>;
export const Toolbar=({published=false,t=0}:{published?:boolean;t?:number})=><div style={{height:62,position:'relative',background:'white',borderBottom:'1px solid #edeef0',fontSize:15,color:'#797b83'}}>
 <div style={{position:'absolute',left:18,top:12,display:'flex',alignItems:'center',gap:12}}><Mark size={37}/><Icon name="chevron" size={13}/></div>
 <div style={{position:'absolute',left:118,top:21}}><Icon name="square" size={20}/></div>
 <div data-control="insert" style={{position:'absolute',left:162,top:10,width:106,height:42,display:'flex',alignItems:'center',justifyContent:'center',gap:9,borderRadius:7,background:press(t,'insert')?'#e7dafb':(done(t,'insert')&&t<15.48)?'#f3eafd':'#f8f8fa',color:(done(t,'insert')&&t<15.48)?purple:'#696471',transform:`scale(${1-.065*press(t,'insert')})`}}><Icon name="plus" size={18}/>Insert</div>
 <span style={{position:'absolute',left:294,top:23}}>Projects</span><div style={{position:'absolute',left:720,top:24,fontSize:13}}>Home <span style={{marginLeft:25,color:'#aaa'}}>fieldnotes.page</span></div>
 <div style={{position:'absolute',right:18,top:10,display:'flex',alignItems:'center',gap:21}}>{['clock','eye','gear','square'].map(n=><Icon key={n} name={n} size={20}/>)}<div style={{background:published?'#1d9d7c':purple,color:'white',padding:'11px 18px',borderRadius:8,display:'flex',gap:12,alignItems:'center'}}>{published?'Published':'Publish'}<Icon size={15} name={published?'check':'chevron'}/></div></div>
 </div>;
const titles=['A little closer to the wild.','The quiet side of the city.','Somewhere worth getting lost.','Out where the light stays.','A different kind of weekend.','Notes from the open road.'];
const pics=['forest','city','mountains','desert','coast','mountains'];
export const PhotoCard=({i=0,large=false,dark=false}:{i?:number;large?:boolean;dark?:boolean})=><div style={{minWidth:0}}><Img src={photo(pics[i%6])} style={{width:'100%',height:large?230:145,objectFit:'cover',display:'block',borderRadius:3}}/><div style={{fontSize:9,color:dark?'#a8a8b0':'#939399',marginTop:8}}>FIELD JOURNAL · 4 MIN READ</div><div style={{fontSize:large?22:15,fontWeight:650,letterSpacing:-.5,marginTop:5,lineHeight:1.12}}>{titles[i%6]}</div><p style={{fontSize:11,lineHeight:1.4,color:dark?'#9c9ca6':'#8a8a92',margin:'7px 0'}}>Stories, places and a fresh perspective. A dispatch from somewhere different.</p></div>;
export const Signup=({vertical=true,big=false}:{vertical?:boolean;big?:boolean})=><div style={{padding:big?24:10,textAlign:'center',background:'white',color:'#171520',borderRadius:4,width:'100%'}}><div style={{fontWeight:700,fontSize:big?30:18,lineHeight:1.17,marginBottom:12}}>The world is worth<br/>a closer look.</div><div style={{display:'flex',flexDirection:vertical?'column':'row',gap:6}}><div style={{border:'1px solid #e0dfe5',padding:big?'16px':'9px',textAlign:'left',fontSize:big?19:12,color:'#b1aeb8',flex:1}}>Your email address</div><div style={{background:purple,color:'white',padding:big?'16px 28px':'9px 16px',fontSize:big?20:12,borderRadius:3}}>Subscribe</div></div></div>;
export const Publication=({t=100,reveal=0,theme=0,darkness=0,archive=false,selected=false,hideSignup=false,assembly=false}:{t?:number;reveal?:number;theme?:number;darkness?:number;archive?:boolean;selected?:boolean;hideSignup?:boolean;assembly?:boolean})=>{
 const dark=theme===2||darkness>.5;const q=m(t,21.2,21.8);const variant=theme===2?true:false;
 return <div style={{width:1000,minHeight:1150,padding:'0 32px 40px',background:dark?'#171719':'#fff',color:dark?'#fff':'#15141c',fontFamily:theme===1?'Georgia,serif':'Geist,sans-serif'}}>
 <div style={{height:65,display:'flex',alignItems:'center',borderBottom:'1px solid '+(dark?'#ffffff25':'#e9e8ed'),fontSize:12,justifyContent:'space-between'}}><b style={{letterSpacing:theme===1?3:0,fontSize:19}}>{theme===1?'THE ATLAS':theme===2?'AFTER HOURS':brand.publication}</b><span>Stories　 About　 Archive</span><div style={{display:'flex',alignItems:'center',gap:13}}>Log in <span style={{background:purple,color:'white',padding:'7px 14px',borderRadius:4}}>Subscribe</span></div></div>
 {(theme===1||theme===2)&&<div style={{textAlign:'center',padding:theme===2?'44px 0 32px':'45px 0',fontSize:theme===2?95:40,fontWeight:850,letterSpacing:-3}}>{theme===2?'THE JOURNAL':'A life less ordinary.'}</div>}
 {!archive&&<div style={{display:'grid',gridTemplateColumns:'1fr 1.23fr 1fr',gap:20,paddingTop:24}}>{[0,1,2].map((i)=>{const q=a(t,reveal+i*.12,reveal+.75+i*.12);return <div key={i} data-card={i} style={{position:'relative',zIndex:assembly?3-i:undefined,transform:assembly?`translate(${(1-q)*(i-1)*92}px,${(1-q)*(-155-i*42)}px) scale(${1+(1-q)*.12}) rotate(${(1-q)*(i-1)*4}deg)`:`translateY(${(1-a(t,reveal+i*.12,reveal+.55+i*.12))*240}px)`,transformOrigin:'50% 0',background:dark?'#171719':'#fff',boxShadow:assembly?`0 ${32*(1-q)}px ${44*(1-q)}px rgba(30,20,46,${.16*(1-q)})`:undefined,opacity:assembly?1:a(t,reveal+i*.12,reveal+.4+i*.12),filter:assembly?`blur(${blur(t,f=>(1-a(f,reveal+i*.12,reveal+.75+i*.12))*(-155-i*42),.18,8)}px)`:undefined}}><PhotoCard i={i} large={i===1} dark={dark}/><div style={{marginTop:20}}>{i===1?<div style={{border:selected?'2px solid '+purple:undefined}}><div style={{visibility:hideSignup?'hidden':'visible'}}><Signup/></div></div>:<PhotoCard i={i+3} dark={dark}/>}</div></div>})}</div>}
 <div style={{marginTop:26,borderTop:'1px solid '+(dark?'#ffffff20':'#e4e4eb'),paddingTop:17,background:darkness>0?`rgba(10,10,12,${darkness})`:undefined,color:darkness>.5?'white':undefined}}><div style={{fontSize:22,fontWeight:750,marginBottom:16}}>{archive?'Archive':'Featured'}</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14}}>{[0,1,2,3].map(i=>{const z=a(t,reveal+i*.09,reveal+.5+i*.09);return <div key={i} style={{opacity:z,transform:`translateY(${(1-z)*70}px)`,filter:`blur(${(1-z)*8}px)`}}><PhotoCard i={i+2} dark={dark}/></div>})}</div></div>
 {archive&&<div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,marginTop:30}}>{[0,1,2,3].map(i=><PhotoCard key={i} i={i}/>)}</div>}
 </div>
};
export const LeftPanel=()=> <div style={{width:220,flexShrink:0,background:'white',height:900,padding:22,fontSize:14,color:'#575562',borderRight:'1px solid #eee'}}><div style={{display:'flex',fontSize:12,gap:15,color:'#34303e',background:'#f6f6f8',padding:10,marginBottom:35}}>Pages <b>Layers</b> Assets</div><p style={{color:'#a4a0aa'}}>Navigation</p><p style={{display:'flex',gap:10}}><Icon name="square" size={17} color={purple}/> Navbar</p><p style={{display:'flex',gap:10}}><Icon name="square" size={17} color={purple}/> Footer</p><p style={{marginTop:35,color:'#a4a0aa'}}>Layers</p>{['Section','Grid','Featured','Subscribe','Archive'].map((n,i)=><p key={n} style={{display:'flex',alignItems:'center',gap:8,paddingLeft:i===1?20:0}}><Icon name="chevron" size={12}/><Icon name="layers" size={15} color={purple}/>{n}</p>)}</div>;
export const Properties=({t=0,orientation=false,plain=false}:{t?:number;orientation?:boolean;plain?:boolean})=><div style={{background:'#fff',width:310,padding:26,color:'#26222f',fontSize:14,boxShadow:plain?undefined:'0 0 1px #dcd9e3,0 8px 36px #8662ba22',borderRadius:plain?0:15}}><div style={{fontSize:18,fontWeight:600,marginBottom:30}}>Signup</div><div style={{color:'#aaa6b0',marginBottom:20}}>Actions <span style={{float:'right'}}>⊙　♧　▤</span></div>{[['Type','▱ Signup'],['Editable','YES　　NO'],['Template','▤ Form'],['Signup flow','↪ Default']].map(([k,v])=><div key={k} style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:21,gap:15}}><span style={{color:'#aaa6b0'}}>{k}</span><span style={{background:'#f6f5f8',borderRadius:6,padding:'10px 12px',minWidth:148,color:k==='Editable'?purple:'#5c5764'}}>{v}</span></div>)}<div style={{borderTop:'1px solid #ece9ef',paddingTop:24,marginTop:12,fontWeight:650,fontSize:16}}>Styles</div>{[['Orientation','↔　　 ↕'],['Padding','0　　□'],['Background','#FFFFFF'],['Border','None'],['Radius','8'],['Width','400　 ●'],['Height','Auto　●'],['Opacity','100　 ●']].map(([k,v],i)=><div key={k} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,marginTop:19}}><span style={{color:'#aaa6b0',fontSize:13}}>{k}</span><span style={{background:'#f7f6f8',borderRadius:5,padding:'10px 13px',minWidth:143,color:i===0||i>3?purple:'#4e4957'}}>{i===0?<span style={{display:'flex',gap:8}}><span style={{padding:'3px 13px',borderRadius:4,background:orientation?'transparent':'white'}}>↔</span><span style={{padding:'3px 13px',borderRadius:4,background:orientation?'white':'transparent'}}>↕</span></span>:v}</span></div>)}</div>;
export const EmptyCanvas=()=> <div style={{width:1000,height:1080,background:'white',padding:40}}>{[0,1,2].map(i=><div key={i} style={{border:'2px dashed #dfdde5',height:i===0?220:240,margin:'20px 0',display:'flex',alignItems:'center',justifyContent:'center',color:'#a8a4af',fontSize:17}}>Drop something wonderful here</div>)}</div>;
export const Editor=({t=100,empty=false,assemble=0,assembly=false,theme=0,darkness=0,published=false,children}:{t?:number;empty?:boolean;assemble?:number;assembly?:boolean;theme?:number;darkness?:number;published?:boolean;children?:React.ReactNode})=><div style={{position:'relative',width:1600,height:930,overflow:'hidden',borderRadius:16,background:'white',boxShadow:'0 0 2px #ddd,0 -10px 44px #ffcbea44,0 18px 50px #7b60d32a',border:'1px solid #efedf3'}}><Toolbar published={published} t={t}/><div style={{display:'flex',position:'relative',height:868}}><LeftPanel/><div style={{width:1135,flexShrink:0,overflow:'hidden',padding:'38px 36px 0',background:'#f0f3f4'}}><div style={{transform:'scale(.995)',transformOrigin:'top left',boxShadow:'0 1px 9px #10102519'}}>{empty?<EmptyCanvas/>:<Publication t={t} reveal={assemble} assembly={assembly} theme={theme} darkness={darkness}/>}</div></div><div style={{transform:'scale(.79)',transformOrigin:'top left',width:245,flexShrink:0}}><Properties plain/></div></div><div style={{position:'absolute',inset:0,pointerEvents:'none'}}>{children}</div></div>;
export const Widgets=({t=0}:{t?:number})=><div style={{position:'relative',width:440,height:640,background:'white',borderRadius:14,boxShadow:'0 2px 7px #15102016,0 15px 45px #a66cd422',color:'#66616f'}}>{[['Layout',['square','grid','layers']],['Elements',['text','image','mail']],['Components',['square','star','globe']],['More',['arrow','phone','plus']]].map(([title,names],row)=><React.Fragment key={String(title)}><div style={{position:'absolute',left:28,top:20+row*143,fontSize:15}}>{title}</div>{(names as string[]).map((n,i)=>{const selected=row===1&&i===1;return <div key={n} data-control={selected?'gallery':undefined} style={{position:'absolute',left:28+i*133,top:53+row*143,width:118,height:86,border:selected&&done(t,'gallery')?'2px solid '+purple:'1px solid #edeaf0',borderRadius:8,display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:10,background:selected&&done(t,'gallery')?'#f1eaff':'white',transform:selected?`scale(${1-.065*press(t,'gallery')})`:undefined}}><Icon size={26} name={n} color={selected&&done(t,'gallery')?purple:'#25202e'}/><span style={{fontSize:12}}>{[['Section','Columns','Stack'],['Text','Gallery','Signup'],['Post','Featured','Social'],['Button','Device','Custom']][row][i]}</span></div>})}</React.Fragment>)}</div>;
export const ColorPicker=({t=0}:{t?:number})=><div style={{width:390,padding:24,background:'white',borderRadius:14,boxShadow:'0 3px 8px #180f2115,0 15px 35px #6e32b822'}}><div style={{fontSize:18,fontWeight:600,marginBottom:24}}>Background color <span style={{float:'right',color:'#aaa'}}>⊕</span></div><div style={{height:265,position:'relative',borderRadius:8,background:'linear-gradient(to top,#0000,#0000),linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,#9450ee)'}}><div style={{position:'absolute',left:mix(12,220,m(t,20,20.8)),top:mix(12,235,m(t,20,20.8)),width:27,height:27,borderRadius:'50%',border:'4px solid white',boxShadow:'0 1px 7px #0007'}}/></div><div style={{height:12,borderRadius:6,marginTop:18,background:'linear-gradient(to right,red,#ff0,#0f0,#0ff,#00f,#f0f,red)'}}/><div style={{display:'flex',gap:10,marginTop:24,fontSize:15,color:'#666'}}><span style={{padding:14,background:'#f7f6f8',borderRadius:6}}>Hex</span><span style={{padding:14,background:'#f7f6f8',borderRadius:6,flex:1}}>{t<20.5?'#FFFFFF':'#171719'}</span><span style={{padding:14}}>100%</span></div><div style={{marginTop:22,display:'flex',gap:12}}>{['#fff','#171719',purple,'#cee8d8','#ffc0ae'].map(c=><span key={c} style={{width:30,height:30,borderRadius:6,background:c,border:'1px solid #ccc'}}/>)}</div></div>;
export const Animations=({t=30}:{t?:number})=><div style={{position:'relative',width:435,height:700,padding:26,borderRadius:19,background:'white',boxShadow:'0 0 2px #d5cddd,0 5px 35px #9152b92a'}}><div style={{fontWeight:600,fontSize:22}}>Enter animation</div>{['Fade','Slide','Grow','Blur','None'].map((n,i)=>{const pr=a(t,29.7+i*.045,30.05+i*.045),sel=done(t,'blurPreset')&&i===3;return <div key={n} style={{position:'absolute',left:26,top:76+i*120,width:383,height:110,display:'flex',alignItems:'center',gap:28,background:sel?'#f1eaff':'#f7f7f8',border:sel?'2px solid '+purple:'2px solid transparent',borderRadius:9,padding:12,transform:`translateY(${(1-pr)*30}px) scale(${1-(i===3?press(t,'blurPreset')*.035:0)})`,opacity:pr}}><div style={{width:160,height:82,background:'#e3e3e6',borderRadius:5,display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:64,height:51,background:'white',borderRadius:6,boxShadow:'0 3px 7px #0002',opacity:n==='Fade'?.65+.35*Math.sin(t*4):1,transform:n==='Slide'?`translateY(${Math.sin(t*4)*10}px)`:n==='Grow'?`scale(${.85+.15*Math.sin(t*4)})`:undefined,filter:n==='Blur'?`blur(${Math.max(0,3*Math.sin(t*4))}px)`:undefined}}/></div><span style={{fontSize:18}}>{n}</span></div>})}</div>;
