import {motionFrame} from './BeatTiming';
import React from 'react';
import {useCurrentFrame} from 'remotion';
import {KineticType,typingBirths,typingWidth,VelocityFilter} from './KineticType';
import {p,lin,slow,focusBlur,center} from './common';
const labels=['FIG','SVG','PSD']; const colors=['#393f50','#817347','#174b73'];
export const Search=({speed=1}:{speed?:number})=>{const local=useCurrentFrame();const f=motionFrame('search',local);const prevF=motionFrame('search',local-1);const reveal=p(f,0,17);const swap=2*p(f,106,141);const searching=slow(f,155,190);const exit=p(f,208,229);const sentence='Where is that design file?';const births=typingBirths(sentence,0,58);const progress=(t:number)=>births.reduce((v,b)=>v+slow(t,b,b+7),0)/births.length;const zAt=(t:number)=>1+.8*slow(progress(t),.27,.84)*(1-slow(t,64,100));const xAt=(t:number)=>-95*slow(progress(t),.3,.88)*(1-slow(t,64,100));const z=zAt(f);const edge=(t:number,side:number)=>xAt(t)+side*typingWidth(sentence,t,0,58,43)*zAt(t)/2;const velocity=Math.max(Math.abs(edge(f,-1)-edge(prevF,-1)),Math.abs(edge(f,1)-edge(prevF,1))); return <><VelocityFilter id="query-velocity" velocity={velocity}/><div style={{...center,width:1000,height:120,opacity:reveal*(1-exit),transform:`translate(calc(-50% - ${exit*145}px + ${xAt(f)}px),-50%) scale(${z*(1-.22*exit)})`,filter:`url(#query-velocity) blur(${(1-reveal)*3+focusBlur(f,155,190,3)}px)`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:43,letterSpacing:-1.6,color:'#202325',whiteSpace:'nowrap'}}>
{f<101?<KineticType text={sentence} f={f} prevF={prevF} start={0} end={58} size={43}/>:<div style={{display:'flex',alignItems:'center',gap:12}}>
<span style={{width:258*(1-searching),overflow:'hidden',opacity:1-searching,filter:`blur(${searching*7}px)`}}>Where is that</span>
<div style={{width:112,height:104,position:'relative',maskImage:'linear-gradient(transparent,black 35%,black 66%,transparent)'}}>{labels.map((s,i)=>{const y=(i-swap)*57;return <div key={s} style={{position:'absolute',left:0,top:32+y,height:40,display:'flex',alignItems:'center',gap:8,opacity:Math.max(.18,1-Math.abs(i-swap)*.72),filter:`blur(${Math.abs(i-swap)*3}px)`,fontSize:30,letterSpacing:-.8}}><div style={{width:37,height:37,borderRadius:8,background:colors[i],color:'white',fontSize:12,letterSpacing:0,display:'flex',alignItems:'center',justifyContent:'center'}}>{s}</div><span>{s}</span></div>})}</div>
<div style={{position:'relative',width:150+115*searching,height:61,display:'flex',alignItems:'center',paddingLeft:6}}><div style={{position:'absolute',inset:'5px 0',background:'#cde9fc',transform:`scaleX(${searching})`,transformOrigin:'left',border:'1px solid #a6d4f0',borderRadius:3}}/><span style={{position:'relative',opacity:1-searching}}>file?</span>{searching>0&&<span style={{position:'absolute',left:13,display:'flex',alignItems:'center',gap:11,fontSize:37,color:'#456c88',opacity:searching,letterSpacing:-1.6}}><span style={{width:25,height:25,border:'2px solid #a2c8e0',borderTopColor:'#426f91',borderRadius:'50%',transform:`rotate(${f*9}deg)`}}/>Searching…</span>}</div>
</div>}
</div></>};
