import React from 'react';import {Brand,task} from '../design';import {Stage,Box,Text,Rule,Arrow,Pill,out,snap} from '../shared';
export const TaskCard:React.FC<{b:Brand;owner?:boolean;due?:boolean;compact?:boolean}>=({b,owner=true,due=true,compact=false})=><div style={{position:'relative',width:compact?480:930,height:compact?340:420,background:b.paper,border:`2px solid ${b.ink}`,padding:compact?30:45,color:b.ink}}>
 <Box x={compact?397:833} y={compact?22:30}><Arrow size={42}/></Box>
 <div style={{display:'flex',gap:compact?17:22,alignItems:'center',marginTop:compact?40:67}}><div style={{width:compact?30:41,height:compact?30:41,border:`2px solid ${b.ink}`,flexShrink:0}}/><span style={{fontSize:compact?78:103,fontWeight:650,letterSpacing:'-.065em',whiteSpace:'nowrap'}}>{task.title}</span></div>
 <div style={{display:'flex',gap:compact?26:140,marginTop:compact?60:52,fontSize:64,fontWeight:550,letterSpacing:'-.06em',whiteSpace:'nowrap'}}><div>{owner?<span>{task.owner}</span>:<div style={{width:150,height:60,borderBottom:`1px dashed ${b.ink}`,opacity:.3}}/>}</div><div>{due?<span>{task.due}</span>:<div style={{width:140,height:60,borderBottom:`1px dashed ${b.ink}`,opacity:.3}}/>}</div></div>
 </div>;
export const TovoExtraction:React.FC<{shot:number;f:number;b:Brand}>=({shot,f,b})=>{
 const p=out(f);let content:React.ReactNode;
 if(shot===6)content=<><Text x={74} y={258} size={157} weight={710}>{task.action}</Text><Box x={83} y={420} w={1050*p} h={17} style={{background:b.accent}}/></>;
 else if(shot===7)content=<><Box x={175} y={157} style={{scale:.93+.07*p,rotate:`${(1-p)*-3}deg`}}><TaskCard b={b} owner={false} due={false}/></Box><Box x={214+(1-p)*-140} y={266+(1-p)*85} w={790} h={127} style={{background:b.accent,opacity:1-p,padding:'9px 30px',fontSize:96,fontWeight:700,letterSpacing:'-.065em'}}>{task.action}</Box></>;
 else if(shot===8)content=<><Box x={79} y={254} w={205} h={205} style={{background:b.accent,borderRadius:150,display:'grid',placeItems:'center',fontSize:135,fontWeight:740,scale:snap(f)}}>{task.owner.charAt(0)}</Box><Text x={337} y={226} size={230} weight={670} style={{translate:`${(1-p)*120}px 0`}}>{task.owner}</Text><Rule x={86} y={526} w={1110}/></>;
 else if(shot===9)content=<><Box x={175} y={157}><TaskCard b={b} due={false}/></Box><Box x={210} y={450} w={244} h={90} style={{border:`3px solid ${b.accent}`,scale:1.3-.3*p,opacity:p,borderRadius:4}}/></>;
 else if(shot===10)content=<><Text x={29} y={46} size={680} serif style={{opacity:.14,lineHeight:.95}}>F</Text><Box x={87} y={273} w={1120} h={246} style={{overflow:'hidden'}}><Text x={0} y={(1-p)*230} size={226} serif>{task.due}.</Text></Box></>;
 else content=<><Box x={81} y={261} w={1117} h={238} style={{background:b.ink,color:b.background,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 47px',rotate:`${(1-p)*-5}deg`,scale:.83+.17*snap(f)}}><span style={{fontFamily:'Instrument',fontSize:183}}>{task.due}</span><div style={{width:110,height:113,border:`2px solid ${b.background}`,borderRadius:8,padding:'19px 15px'}}><div style={{height:3,background:b.background,marginBottom:20}}/><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:9}}>{Array.from({length:6},(_,i)=><div key={i} style={{height:10,background:b.background}}/>)}</div></div></Box></>;
 return <Stage brand={b} bg={shot===10?b.accent:b.background} >{content}</Stage>;
};
